### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by raffaello-camoriano** [Ommac/ior#1]
- [x] Add labels rebalancing
- [x] Check validation set at step k. It should be cumulative across updates and classes
- [x] Use real images
- [x] Add rebalancing of validation error
- [x] Use {+1,-1} coding instead of {0,1}
